
title: Meetu
logo: /assets/img/headshot_circle.png
description: Data Scientist, helping the automotive industry in navigating the data landscape - utilizing data, analysis and insights to facilitate informed decision-making
show_downloads: true
theme: jekyll-theme-minimal
