
title: Meetu
logo: /assets/img/meetuPic.jpg
description: Data Scientist | Machine Learning Enthusiast | utilizing data to facilitate informed decision-making
show_downloads: true
theme: jekyll-theme-minimal
